TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += tizr.db
DBD += tizr.dbd

#=======================================
include $(TOP)/configure/RULES